import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import "./globals.css";
import signIn from "front-end\app\signIn\page.js";

export const metadata = {
  title: "novix ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/*
        The GeistSans.variable and GeistMono.variable classes provide the CSS variables
        to the rest of the application.
      */}
      <body
        className={`${GeistSans.variable} ${GeistMono.variable} antialiased`}
      >
        

        <signIn/>

       
      </body>
    </html>
  );
}