import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";

export const metadata = {
  title: "novix ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/*
        The GeistSans.variable and GeistMono.variable classes provide the CSS variables
        to the rest of the application.
      */}
      <body
        className={`${GeistSans.variable} ${GeistMono.variable} antialiased`}
      >
        <header>
          <Header />
        </header>

        <main>{children}</main>

        <Footer />
      </body>
    </html>
  );
}